# Generated by Django 3.1.3 on 2021-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20211013_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktask',
            name='task_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='task_msg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='运行消息'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='task_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间'),
        ),
    ]
