# Generated by Django 3.1.3 on 2022-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_checktask_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktask',
            name='scan_type',
            field=models.CharField(choices=[('webscan', 'webscan'), ('servicescan', 'servicescan')], default='webscan', max_length=60, verbose_name='扫描类型'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='说明备注'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='xray_address',
            field=models.CharField(default=1, max_length=500, verbose_name='xray扫描地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checktask',
            name='task_state',
            field=models.CharField(choices=[('runing', 'runing'), ('finish', 'finish'), ('notstarted', 'notstarted')], default='notstarted', max_length=60, verbose_name='任务状态'),
        ),
    ]
