# Generated by Django 3.1.3 on 2021-09-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseste',
            old_name='Locat_type',
            new_name='locat_type',
        ),
        migrations.RenameField(
            model_name='caseste',
            old_name='operate',
            new_name='ope_type',
        ),
    ]
