# Generated by Django 3.1.3 on 2021-08-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjname', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('prjalias', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目别名')),
                ('deploypath', models.CharField(blank=True, max_length=200, null=True, verbose_name='部署路径')),
                ('depldescr', models.TextField(blank=True, null=True, verbose_name='部署路径')),
            ],
            options={
                'verbose_name': '部署信息',
                'verbose_name_plural': '部署信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('isenabled', models.BooleanField(default=True, verbose_name='项目状态')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='版本版本')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=32, verbose_name='创建人')),
                ('Updater', models.CharField(max_length=32, verbose_name='更新人')),
                ('deployinfos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.deployinfo', verbose_name='部署信息')),
                ('prjcet_personliable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属负责人')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
