# Generated by Django 3.1.3 on 2021-08-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Updater',
            new_name='updater',
        ),
        migrations.AddField(
            model_name='project',
            name='prjcet_participant',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='项目参与者'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prjcet_personliable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prjcet', to=settings.AUTH_USER_MODEL, verbose_name='所属负责人'),
        ),
    ]
