# Generated by Django 3.1.3 on 2021-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210818_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployinfo',
            name='depldescr',
            field=models.TextField(blank=True, null=True, verbose_name='部署描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updater',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人'),
        ),
    ]
