# Generated by Django 3.1.3 on 2021-09-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210818_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployinfo',
            name='deploypath',
            field=models.CharField(default=1, max_length=200, verbose_name='部署路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='prjalias',
            field=models.CharField(default=2, max_length=32, verbose_name='项目别名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployinfo',
            name='prjname',
            field=models.CharField(max_length=100, unique=True, verbose_name='部署名称'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=32, verbose_name='模块名称')),
                ('module_alias', models.CharField(max_length=32, verbose_name='模块别名')),
                ('isenabled', models.BooleanField(default=True, verbose_name='状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('maintainer', models.CharField(max_length=32, verbose_name='维护者')),
                ('projcet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '功能模块',
                'verbose_name_plural': '功能模块',
                'db_table': 'Module',
            },
        ),
    ]
