# Generated by Django 3.1.3 on 2021-09-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210902_1207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table=None,
        ),
    ]
