# Generated by Django 3.1.3 on 2021-08-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oauth.department', verbose_name='部门'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oauth.position', verbose_name='职位'),
            preserve_default=False,
        ),
    ]
