# Generated by Django 3.1.3 on 2021-08-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20210809_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='users',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.position', verbose_name='职位'),
        ),
    ]
